# Generated by Django 5.0 on 2023-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=20)),
            ],
        ),
    ]
